version: "3.7"

services:
  deno:
    image: "deno-docker:0.0.1"
    build: .
    volumes:
        - ./:/app
    ports:
      - "7777:8000"
    networks: 
      - deno

networks:
  deno: {}